### ISSUE TITLE
Add container property 

### ISSUE THREAD

**Issue by cgreg21** [optimistex/ngx-select-ex#47]
Could you please add an additional property container (container="body") for injecting DOM in the body when select in a div with overflow hidden or auto?

Merci.

**Comment by optimistex** [comment]
The component uses the `ng-template`. 
It ensured by the code:
https://github.com/optimistex/ngx-select-ex/blob/e0bca6c0d0c6b1f87cbbc1e0b0c9e2111cdf677b/src/app/lib/ngx-select/ngx-select.component.html#L105-L111

Please, consider using the templates:
https://github.com/optimistex/ngx-select-ex#templates

**Comment by lneningerBelzona** [comment]
I have no clue how to use a named template into the select. Could you elaborate a little more?

**Comment by optimistex** [comment]
@lneningerBelzona Did you read the documentation: https://github.com/optimistex/ngx-select-ex#templates

**Comment by amiram** [comment]
I also have the same problem. I don't see how templates are related to that.

**Comment by lneninger** [comment]
I fixed the problem. Was not ngx-select but ngx-datatable component. Thanks for your support.

**Comment by Disane87** [comment]
Problem still persists. There is no property for attaching the list of items to the body:
![image](https://user-images.githubusercontent.com/956158/51550599-fbb8bc00-1e6c-11e9-9226-cd90f4bc1352.png)

**Comment by akvaliya** [comment]
I am also facing the same issue as @Disane87 . Anyone have any idea?

**Comment by optimistex** [comment]
The general issue that other components overlay the drop down menu.
The drop down menu has `z-index: 1000`.

@lneningerBelzona 
https://github.com/optimistex/ngx-select-ex/issues/47#issuecomment-400450043
Your issue could be fixed by change through the class `.ngx-select__choices`:
```
.ngx-select__choices {
   z-index: 9999;
}
```

@Disane87 Apparently the reason of your issue is `overflow: hidden` on the element that contains `ngx-select` component. Consider to change your CSS and get rid from `overflow: hidden` on the parent component.

**Comment by cgreg21** [comment]
Exemple : https://ng-select.github.io/ng-select#/append-to-element

**Comment by optimistex** [comment]
@cgreg21 
Thank you for the example!
Made as a different issue like an enhancement: https://github.com/optimistex/ngx-select-ex/issues/160

**Comment by Dj-jom2x** [comment]
news? for append to ?

**Comment by optimistex** [comment]
@Dj-jom2x Thanks for reminder. I still did not have a time to do that. I'll try to...
From other side, If you find a time to make a pull request it will help a lot.
